from types import TracebackType
from typing import Callable, Generic, TypeVar
from typing_extensions import Self, TypedDict

from mistletoe import block_token, span_token
from mistletoe.core_tokens import _DestTitle
from mistletoe.token import Token

_ResultT = TypeVar("_ResultT")

class _RenderMap(TypedDict, Generic[_ResultT]):
    Strong: Callable[[span_token.Strong], _ResultT]
    Emphasis: Callable[[span_token.Emphasis], _ResultT]
    InlineCode: Callable[[span_token.Emphasis], _ResultT]
    RawText: Callable[[span_token.RawText], _ResultT]
    Strikethrough: Callable[[span_token.Strikethrough], _ResultT]
    Image: Callable[[span_token.Image], _ResultT]
    Link: Callable[[span_token.Link], _ResultT]
    AutoLink: Callable[[span_token.AutoLink], _ResultT]
    EscapeSequence: Callable[[span_token.EscapeSequence], _ResultT]
    Heading: Callable[[block_token.Heading], _ResultT]
    SetextHeading: Callable[[block_token.Heading], _ResultT]
    Quote: Callable[[block_token.Heading], _ResultT]
    Paragraph: Callable[[block_token.Heading], _ResultT]
    CodeFence: Callable[[block_token.Heading], _ResultT]
    BlockCode: Callable[[block_token.Heading], _ResultT]
    List: Callable[[block_token.Heading], _ResultT]
    ListItem: Callable[[block_token.Heading], _ResultT]
    Table: Callable[[block_token.Table], _ResultT]
    TableRow: Callable[[block_token.TableRow], _ResultT]
    TableCell: Callable[[block_token.TableCell], _ResultT]
    ThematicBreak: Callable[[block_token.ThematicBreak], _ResultT]
    LineBreak: Callable[[span_token.LineBreak], _ResultT]
    Document: Callable[[block_token.Document], _ResultT]

class BaseRenderer(Generic[_ResultT]):
    render_map: _RenderMap[_ResultT]
    footnotes: dict[str, _DestTitle]
    def __init__(self, *extras: type[Token]) -> None: ...
    def render(self, token: Token) -> _ResultT: ...
    def render_inner(self, token: Token) -> _ResultT: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exception_type: type[BaseException] | None, exception_val: BaseException | None, traceback: TracebackType | None
    ) -> None: ...
    def render_raw_text(self, token: span_token.RawText) -> _ResultT: ...
    def render_strong(self, token: span_token.Strong) -> _ResultT: ...
    def render_emphasis(self, token: span_token.Emphasis) -> _ResultT: ...
    def render_inline_code(self, token: span_token.InlineCode) -> _ResultT: ...
    def render_strikethrough(self, token: span_token.Strikethrough) -> _ResultT: ...
    def render_image(self, token: span_token.Image) -> _ResultT: ...
    def render_link(self, token: span_token.Link) -> _ResultT: ...
    def render_auto_link(self, token: span_token.AutoLink) -> _ResultT: ...
    def render_escape_sequence(self, token: span_token.EscapeSequence) -> _ResultT: ...
    def render_line_break(self, token: span_token.LineBreak) -> _ResultT: ...
    def render_heading(self, token: block_token.Heading) -> _ResultT: ...
    def render_quote(self, token: block_token.Quote) -> _ResultT: ...
    def render_paragraph(self, token: block_token.Paragraph) -> _ResultT: ...
    def render_block_code(self, token: block_token.BlockCode) -> _ResultT: ...
    def render_list(self, token: block_token.List) -> _ResultT: ...
    def render_list_item(self, token: block_token.ListItem) -> _ResultT: ...
    def render_table(self, token: block_token.Table) -> _ResultT: ...
    def render_table_cell(self, token: block_token.TableCell) -> _ResultT: ...
    def render_table_row(self, token: block_token.TableRow) -> _ResultT: ...
    def render_thematic_break(self, token: block_token.ThematicBreak) -> _ResultT: ...
    def render_document(self, token: block_token.Document) -> _ResultT: ...
