from _typeshed import Incomplete

class FileWrapper:
    lines: Incomplete
    def __init__(self, lines) -> None: ...
    def __next__(self): ...
    def __iter__(self): ...
    def anchor(self) -> None: ...
    def reset(self) -> None: ...
    def peek(self): ...
    def backstep(self) -> None: ...

def tokenize(iterable, token_types): ...
def tokenize_block(iterable, token_types): ...
def make_tokens(parse_buffer): ...

class ParseBuffer(list):
    loose: bool
    def __init__(self, *args) -> None: ...
