from _typeshed import Incomplete

version_str: Incomplete

def main(args) -> None: ...
def convert(filenames, renderer) -> None: ...
def convert_file(filename, renderer) -> None: ...
def interactive(renderer) -> None: ...
def parse(args): ...
