from _typeshed import Incomplete

from mistletoe.base_renderer import BaseRenderer

verb_delimiters: Incomplete

class LaTeXRenderer(BaseRenderer):
    packages: Incomplete
    verb_delimiters: Incomplete
    def __init__(self, *extras) -> None: ...
    def render_strong(self, token): ...
    def render_emphasis(self, token): ...
    def render_inline_code(self, token): ...
    def render_strikethrough(self, token): ...
    def render_image(self, token): ...
    def render_link(self, token): ...
    def render_auto_link(self, token): ...
    @staticmethod
    def render_math(token): ...
    def render_escape_sequence(self, token): ...
    def render_raw_text(self, token, escape: bool = ...): ...
    def render_heading(self, token): ...
    def render_quote(self, token): ...
    def render_paragraph(self, token): ...
    def render_block_code(self, token): ...
    def render_list(self, token): ...
    def render_list_item(self, token): ...
    def render_table(self, token): ...
    def render_table_row(self, token): ...
    def render_table_cell(self, token): ...
    @staticmethod
    def render_thematic_break(token): ...
    @staticmethod
    def render_line_break(token): ...
    def render_packages(self): ...
    def render_document(self, token): ...
